import type { Metadata } from "next";
import { CookiesProvider } from "next-client-cookies/server";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { StyledEngineProvider } from "@mui/material";
import MuiSetup from "../utils/mui-setup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome to Next.js!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StyledEngineProvider injectFirst>
          <MuiSetup>
            <CookiesProvider>{children}</CookiesProvider>
          </MuiSetup>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
