import React from "react";
import "./auth.css";

export const metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};
export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className='auth-container'
      // style={{
      //   backgroundImage: `url(${imageBg.src})`,
      //   backgroundRepeat: 'no-repeat',
      //   backgroundPosition: 'center',
      //   backgroundSize: 'cover',
      // }}
    >
      {children}
    </div>
  );
}
