import Sidebar from "@/src/components/Sidebar/Sidebar";
import { BadgeProvider } from "@/src/provider/BadgeProvider";
import { Box } from "@mui/joy";
import React from "react";

export const metadata = {
  title: "Cafe App",
  description: "Generated by create next app",
};

// eslint-disable-next-line react/prop-types
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <BadgeProvider>
        <Box sx={{ display: "flex", minHeight: "100dvh" }}>
          <Sidebar />

          <Box
            component='main'
            className='MainContent'
            sx={{
              px: { xs: 2, md: 6 },
              pt: { xs: "calc(12px + var(--Header-height))", md: 3 },
              pb: { xs: 2, sm: 2, md: 3 },
              flex: 1,
              display: "flex",
              flexDirection: "column",
              minWidth: 0,
              height: "100dvh",
              gap: 1,
              overflow: "auto",
            }}
          >
            {children}
          </Box>
        </Box>
      </BadgeProvider>
      {/* <Navbar rootPath='/app' /> */}
      {/* <main className='main-container'>{children}</main> */}
    </>
  );
}
