name: pos_cafe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter_rating_bar: ^4.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter:
    sdk: flutter
  # carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  google_nav_bar: ^5.0.6
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  animated_svg: ^2.0.0
  flutter_cache_manager: ^3.3.1
  skeletons: ^0.0.3
  provider: ^6.1.1
  intl: ^0.19.0
  flutter_sticky_header: ^0.6.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/favorit/
